[project]
name = "image-latent-transformer"
description = "Decode text (bytes) from an image"
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amit@sign.mt" },
]
readme = "README.md"
dependencies = [
    "transformers[torch]",
    "datasets",
    "Pillow", # For AutoImageProcessor
    "torchvision", # For use_fast=True
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

train = [
    "modal"
]

[tool.setuptools]
packages = [
    "image_latent_transformer",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "C90", # mccabe complexity
    "I", # isort
    "N", # pep8-naming
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "PT", # flake8-pytest-style
    "W605", # invalid escape sequence
    "BLE", # flake8-blind-except
    "TRY", # tryceratops
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["image_latent_transformer", "tests"]
