name: Dockerfile build test

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yaml'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag test-build:latest \
            .
