name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install Conda Dependencies
        run: conda install -c conda-forge pycairo pygobject manimpango -y

      - name: Install Package
        run: pip install ".[dev]"

      - name: Test Code
        run: pytest .
